name: Create Tag

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/github-script@v5
        id: code-version
        with:
          script: .github/getCodeVersion.sh
          result-encoding: string

      - name: Create new version tag
        uses: actions/github-script@v5
        env:
          TAG_NAME: ${{steps.code-version.outputs.result}}
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/testetag`,
              sha: context.sha
            })
